---
version: '3.3'

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    expose:
      - 2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: $MYSQL_ROOT_PASSWORD
      database__connection__database: ghost
      url: $APP_URL
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ghost-web.middlewares=authelia@docker"
      - "traefik.http.routers.ghost-web.entrypoints=http"
      - "traefik.http.routers.ghost-web.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.ghost-secure.entrypoints=https"
      - "traefik.http.routers.ghost-secure.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.ghost-secure.middlewares=authelia@docker"
      - "traefik.http.routers.ghost-secure.tls.certresolver=letsencrypt"
    networks:
      - default
      - traefik
    
  db:
    image: mysql:$MYSQL_VERSION
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

networks:
  traefik:
    external: true
